---
title: "Exploratory Data Analysis"
author: "Data Sci Buds (Pranav, Lily, Minjee, Tammy)"
date: '2022-04-27'
output:
  html_document:
    toc: true
    toc_float: true
    highlight: "tango"
editor_options: 
  chunk_output_type: console
---

```{r include=FALSE}
#load packages 
library(tidyverse)
library(tidymodels)
library(janitor)
library(naniar)
library(ggplot2)
```

```{r}
#read in 
superstore_dat <- read_csv(file = "data/unprocessed/Superstore_data.csv") %>% 
  clean_names()
```

# Initial Split of Data

```{r}
# initial split 
#split data
superstore_split <- 
  initial_split(superstore_dat,
                prop = .8,
                strata = profit)

superstore_train <- training(superstore_split)
superstore_test <- testing(superstore_split)
```

```{r}
#folds
superstore_resamples <- 
  superstore_train %>% 
  vfold_cv(v = 5, repeats = 3, strata = profit)
```

# Initial Overview of Data

```{r}
#9994 observations and 21 features 
dim(superstore_dat)
```

```{r}
#check for missingness 
miss_var_table <- miss_var_table(superstore_train)
miss_var_summary <- miss_var_summary(superstore_train)
gg_miss_var <- gg_miss_var(superstore_train)
```

```{r}
#no missingness in the data 
miss_var_table
miss_var_summary
gg_miss_var
```

# Essential Findings

## Response Variables

```{r}
# univariate profit graph
ggplot(superstore_dat, aes(profit)) +
  geom_density() +
  xlim(c(-200, 300)) +
  ggtitle("Profit or Loss Incurred from Sales")
```

```{r}
# univariate sales graph
ggplot(superstore_dat, aes(sales)) +
  geom_density() +
  xlim(c(0,1000)) +
  ggtitle("Sales of Products")
```

## Important Predictor Variables

```{r}
# univariate category graph
ggplot(superstore_dat, aes(category)) +
  geom_bar() +
  ggtitle("Category of Products Sold")
```

```{r}
# univariate subcategory graph
ggplot(superstore_dat, aes(sub_category)) +
  geom_bar() +
  ggtitle("Subcategory of Products Sold") +
  coord_flip()
```

```{r}
#univariate region graph
ggplot(superstore_dat, aes(region)) +
  geom_bar() +
  ggtitle("Region where Customer is From")
```

```{r}
# univariate discount graph
ggplot(superstore_dat, aes(discount)) +
  geom_density() +
  ggtitle("Discount Provided")
```

```{r}
# univariate state graph
ggplot(superstore_dat, aes(state)) +
  geom_bar() +
  ggtitle("Customer State of Residence") +
  coord_flip()
```

```{r}
# bivariate sub-category graph
superstore_dat %>%
  group_by(sub_category) %>%
  mutate(avg_prf = mean(profit)) %>%
  ggplot(aes(sub_category, avg_prf)) +
  geom_bar(stat="identity", position=position_dodge()) +
  labs(
    title = "Average Profit for Different Sub-Categories",
    x = "Subcategory",
    y = "Average Profit"
  ) +
  theme(axis.text.x = element_text(angle = 90))

# same plot not including copiers  
superstore_dat %>%
  group_by(sub_category) %>%
  mutate(avg_prf = mean(profit)) %>%
  ggplot(aes(sub_category, avg_prf)) +
  geom_bar(stat="identity", position=position_dodge()) +
  scale_y_continuous(limits = c(-60, 60),
                     breaks = seq(-60, 60, 20)) +
  labs(
    title = "Average Profit for Different Sub-Categories",
    subtitle = "(Not including Copiers sub-category)",
    x = "Subcategory",
    y = "Average Profit"
  ) +
  theme(axis.text.x = element_text(angle = 90))
```

```{r}
# bivariate discount graph - profit
superstore_dat %>%
  group_by(discount) %>%
  mutate(avg_prf = mean(profit)) %>%
  ggplot(aes(discount, avg_prf)) +
  geom_bar(stat="identity", position=position_dodge(), width = 0.04) +
  scale_x_continuous(limits = c(-0.05, 0.85),
                     breaks = seq(-0.1, 0.8, 0.1),
                     expand = c(0,0)) +
  labs(
    title = "Average Profit for Different Discount Values",
    x = "Discount Value",
    y = "Average Profit"
  )

# bivariate discount graph - sales
superstore_dat %>%
  group_by(discount) %>%
  mutate(avg_sls = mean(sales)) %>%
  ggplot(aes(discount, avg_sls)) +
  geom_bar(stat="identity", position=position_dodge(), width = 0.04) +
  scale_x_continuous(limits = c(-0.05, 0.85),
                     breaks = seq(-0.1, 0.8, 0.1),
                     expand = c(0,0)) +
  labs(
    title = "Average Sales for Different Discount Values",
    x = "Discount Value",
    y = "Average Sales"
  )
```

```{r}
# bivariate table - top 10 states in sales
superstore_dat %>%
  group_by(state) %>%
  mutate(average_sales = mean(sales)) %>%
  select(state, average_sales) %>%
  arrange(desc(average_sales)) %>%
  distinct() %>%
  head(10)

# bivariate table - top 10 states in profit 
superstore_dat %>%
  group_by(state) %>%
  mutate(average_profit = mean(profit)) %>%
  select(state, average_profit) %>%
  arrange(desc(average_profit)) %>%
  distinct() %>%
  head(10)
```

```{r}
# region sales contribution and segment composition
superstore_dat %>%
  group_by(region) %>%
  mutate(avg_sls = mean(sales)) %>%
  ggplot(aes(x = region, y = avg_sls, fill = segment)) +
  geom_bar(stat="identity") +
  scale_y_continuous(limits = c(0, 750000),
                     breaks = seq(0, 800000, 100000),
                     expand = c(0,0),
                     labels = comma) +
  labs(
    title = "Region Sales and Segment Composition",
    x = "Region",
    y = "Average Sales",
    fill = "Customer Segment"
  ) + 
  theme_light()

# west region state sales and segment
superstore_dat %>%
  filter(region == "West") %>%
  group_by(state) %>% 
  mutate(avg_sls = mean(sales)) %>%
  ggplot(aes(x = state, y = avg_sls, fill = segment)) +
  geom_bar(stat="identity") +
  scale_y_continuous(limits = c(0, 475000),
                     breaks = seq(0, 500000, 50000),
                     expand = c(0,0),
                     labels = comma) +
  labs(
    title = "Western States Sales and Segment Composition",
    x = "State",
    y = "Average Sales",
    fill = "Customer Segment"
  ) + 
  theme_light() +
  theme(axis.text.x = element_text(angle = 90))
```


# Secondary Findings

## Standard Variable Explorations

```{r}
#univariate quantity graph
ggplot(superstore_dat, aes(quantity)) +
  geom_density() +
  ggtitle("Quantity of the Product Ordered") 
```

```{r}
# univariate ship mode graph
ggplot(superstore_dat, aes(ship_mode)) +
  geom_bar() +
  ggtitle("Order Ship Mode")  
```










