---
title: "Codebook"
author: "Data Sci Buds (Pranav, Lily, Minjee, Tammy)"
date: '2022-06-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Row ID** 

Unique ID for each row

**Order ID**

Unique Order ID for each Customer

**Order Date** 

Order Date of the product.

**Ship Date** 
Shipping Date of the Product.

**Ship Mode**
Shipping Mode specified by the Customer.

**Customer ID**
Unique ID to identify each Customer.

**Customer Name** 
Name of the Customer.

**Segment** 
The segment where the Customer belongs.

**Country** 
Country of residence of the Customer.

**City** 
City of residence of of the Customer.

**State** 
State of residence of the Customer.

**Postal Code** 
Postal Code of every Customer.

**Region** 
Region where the Customer belong.

**Product ID** 
Unique ID of the Product.

**Category** 
Category of the product ordered.

**Sub-Category** 
Sub-Category of the product ordered.

**Product Name**
Name of the Product

**Sales**
Sales of the Product.

**Quantity**
Quantity of the Product.

**Discount**
Discount provided.

**Profit** 
Profit/Loss incurred.

## Citation 

https://www.kaggle.com/datasets/vivek468/superstore-dataset-final