---
title: "Data Memo"
author: "Data Sci Buds (Pranav, Lily, Minjee, Tammy)"
date: '2022-04-12'
output:
  html_document:
    toc: true
    toc_float: true
    highlight: "tango"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Proposed Project Timeline

* 4/18-24: Clean data and perform initial EDA
* 4/25-5/8: Split data, make recipes, fit and tune models
* 5/9-15: Collect and compare metrics, fit best model to test set and evaluate performance.
* 5/16-29: Write narratives and executive summary
* 6/5: complete project

<br>

## Overview of the Dataset

Our dataset is analyzing certain products for a superstore giant. They want to know what areas, categories, and customer segments to avoid in order to have the highest sales or profit. They also want to know which products to focus on. 
<br><br>
Each row represents a customer transaction for a specific product, and the columns (variables) give information about the transaction. The variables include: 

* product name
* product sales
* quantity of the product sold (to specific customer)
* discounts
* profit or loss incurred from the sale of the specific product. 

Along with this information, there is also buyer information including customer name, city and state residence of the customer, and region where the customer resides.
<br><br>
This dataset is a simple download from Kaggle. It contains almost 10,000 observations and 21 variables. 
<br><br>
There is no need to join any data sources together. There does not appear to be any missingness in the dataset. It is very cleaned and useable. 

<br>

## Potential Research Questions

The profit from each transaction greatly varied. Since the store's objective is to maximize profit, I think it would be interesting to answer the following: 

* How can we best predict profit given information about a particular transaction?

This is a **predictive question** since we want to predict profit—we don't care how we get to this prediction, we just want an accurate profit prediction. Since the response variable, profit, is numeric, this is a regression problem. We suspect that useful variables to predict price would be product name, product category, quantity sold, and sales. Another predictive question would be:

* How can we best predict the region a particular transaction took place in?

This also is a **predictive** question, since we only want to predict region. The response variable, region (which gives a region in the US), is categorical, so this is a classification problem. We would remove other location variables (like city and state) from our model, because these would perfectly predict the region. We want to see if we can predict region based on the sale made, so example variables we would want to use to predict would be product name, quantity sold, and category of product sold. This would be interesting to see—do people in different regions of the US display different buying habits? This could help the store choose what to sell in different parts of the US. 

<br>

## Difficulties
Some difficulties we might face could be regarding the time it takes to run all of the models with such a large database. In order to increase accuracy, we can increase the number of folds and repetitions for the models, but that might increase the time it takes for the models to finish running. 
<br>
In addition, it may also be difficult to assess date variables (e.g. shipping date) as a part of our model recipe. A way to combat this is to change the date into strings noting the specific month, year or day of the week.
<br>

## Citation 

https://www.kaggle.com/datasets/vivek468/superstore-dataset-final

## Github Repo
[https://github.com/STAT301III/final-project-data-sci-buds.git](https://github.com/STAT301III/final-project-data-sci-buds.git){target="_blank"}

